[package]
name = "xml-exporter"
version = "0.2.2"
authors = ["Ignas LapÄ—nas <ignas@lapenas.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
either = "1.6.1"
env_logger = ""
log = "0.4.11"
postgres = "0.19.0"
regex = "1.4.2"
